version: '3'
services:
  app:
    build: .
    command: npm start
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  dbdata: