version: '3.8'
services:
  app:
    image: node:lts
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm i && npm run start:dev"
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: